window.SITE_CONTENT = {
  "name": "Éamonn Needham",
  "role": "Postdoctoral Researcher",
  "introduction": "I am a volcanologist, geochemist, and experimental petrologist at the University of California, Davis. I use experiments, microscopy, and geochemical measurements to study magmatic processes on Earth and the Moon.",
  "biography": "My research focuses on volcanic fragmentation, mineral growth, diffusion, and the interpretation of geochemical records.",
  "groupUrl": "https://jwatkins529.github.io/",
  "linkedInUrl": "https://www.linkedin.com/in/eamonn-needham-178535163",
  "email": "eneedham@ucdavis.edu",
  "portrait": "assets/field-portrait.webp",
  "cv": "assets/eamonn-needham-cv-oct-2026.pdf",
  "poster": "",
  "photos": [
    {
      "id": "mountain-landscape",
      "title": "Mt. Hood, Oregon",
      "category": "Field & landscapes",
      "thumbnail": "assets/mountain-landscape-thumb.webp",
      "full": "assets/mountain-landscape.webp",
      "alt": "Mt. Hood above rocky slopes and conifer forest under a clear blue sky.",
      "caption": "Mt. Hood, Oregon.",
      "credit": "From Éamonn Needham’s collection",
      "placeholder": false,
      "source": "",
      "wide": true,
      "position": "center 38%",
      "gallery": true
    },
    {
      "id": "field-portrait",
      "title": "Fieldwork",
      "category": "Field & landscapes",
      "thumbnail": "assets/field-portrait-thumb.webp",
      "full": "assets/field-portrait.webp",
      "alt": "Éamonn wearing a field hat and backpack, holding a rock sample in a rugged landscape.",
      "caption": "Éamonn holding a rock sample in the field.",
      "credit": "From Éamonn Needham’s collection",
      "placeholder": false,
      "source": "",
      "wide": false,
      "position": "center 40%",
      "gallery": true
    },
    {
      "id": "lab",
      "title": "Experimental laboratory",
      "category": "Laboratory",
      "thumbnail": "assets/lab-thumb.webp",
      "full": "assets/lab.webp",
      "alt": "Blue laboratory press beside a large pressure gauge, workbench, and orange lifting equipment.",
      "caption": "Laboratory equipment for experiments on rocks and minerals.",
      "credit": "From Éamonn Needham’s collection",
      "placeholder": false,
      "source": "",
      "wide": false,
      "position": "center",
      "gallery": true
    },
    {
      "id": "poster-session",
      "title": "Conference poster session",
      "category": "Presentations",
      "thumbnail": "assets/poster-session-thumb.webp",
      "full": "assets/poster-session.webp",
      "alt": "Éamonn standing beside a scientific poster and pointing toward its figures.",
      "caption": "Presenting research at a scientific conference.",
      "credit": "From Éamonn Needham’s collection",
      "placeholder": false,
      "source": "",
      "wide": true,
      "position": "center",
      "gallery": true
    },
    {
      "id": "experiment",
      "title": "Experimental assembly",
      "category": "Laboratory",
      "thumbnail": "assets/experiment-thumb.webp",
      "full": "assets/experiment.webp",
      "alt": "A small cylindrical experimental assembly on a green cutting mat beside a ruler.",
      "caption": "An experimental assembly beside a ruler.",
      "credit": "From Éamonn Needham’s collection",
      "placeholder": false,
      "source": "",
      "wide": false,
      "position": "center 65%",
      "contain": true,
      "gallery": true
    },
    {
      "id": "science-talk",
      "title": "Public science talk",
      "category": "Presentations",
      "thumbnail": "assets/science-talk-thumb.webp",
      "full": "assets/science-talk.webp",
      "alt": "A speaker and seated audience below a projection screen in a timber-framed venue.",
      "caption": "A public science presentation.",
      "credit": "From Éamonn Needham’s collection",
      "placeholder": false,
      "source": "",
      "wide": false,
      "position": "center",
      "gallery": true
    },
    {
      "id": "mountain-portrait",
      "title": "In the mountains",
      "category": "Field & landscapes",
      "thumbnail": "assets/mountain-portrait-thumb.webp",
      "full": "assets/mountain-portrait.webp",
      "alt": "Éamonn seated on a rocky viewpoint beneath clouds and snow-covered mountains.",
      "caption": "A photograph from a mountain viewpoint.",
      "credit": "From Éamonn Needham’s collection",
      "placeholder": false,
      "source": "",
      "wide": false,
      "position": "center 47%",
      "contain": true,
      "gallery": true
    },
    {
      "id": "graduation",
      "title": "Graduation",
      "category": "Milestones",
      "thumbnail": "assets/graduation-thumb.webp",
      "full": "assets/graduation.webp",
      "alt": "Éamonn in doctoral regalia holding a diploma beside a palm-lined walkway.",
      "caption": "Doctoral graduation.",
      "credit": "From Éamonn Needham’s collection",
      "placeholder": false,
      "source": "",
      "wide": false,
      "position": "center 60%",
      "gallery": true
    },
    {
      "id": "lunar-breccia",
      "title": "Lunar breccia",
      "category": "Research images",
      "thumbnail": "assets/lunar-breccia.webp",
      "full": "assets/lunar-breccia.webp",
      "alt": "A lunar breccia thin section with seven outlined domains and a 1 mm scale bar.",
      "caption": "Lunar breccia thin section, sample 12013,7. The annotated domains and scale bar are retained from the supplied figure.",
      "credit": "Figure supplied by Éamonn Needham",
      "placeholder": false,
      "source": "",
      "contain": true,
      "background": "#111713",
      "gallery": true
    },
    {
      "id": "lunar-clast",
      "title": "Lunar clast — SEM",
      "category": "Research images",
      "thumbnail": "assets/lunar-clast.webp",
      "full": "assets/lunar-clast.webp",
      "alt": "SEM image of a felsic clast in lunar breccia, with zircon, plagioclase, melt, and breccia matrix labelled; scale bar 50 micrometres.",
      "caption": "SEM image of a felsic clast in lunar breccia, sample 73235,60 (\"Cracker\").",
      "credit": "Figure supplied by Éamonn Needham",
      "placeholder": false,
      "source": "",
      "contain": true,
      "background": "#e5e8e1",
      "gallery": true
    },
    {
      "id": "titaniq",
      "title": "TitaniQ project",
      "category": "Research images",
      "thumbnail": "assets/titaniq.webp",
      "full": "assets/titaniq.webp",
      "alt": "Electron microscopy image showing the face and surrounding surfaces of a crystal in the TitaniQ project.",
      "caption": "Crystal image from the TitaniQ project.",
      "credit": "Figure supplied by Éamonn Needham",
      "placeholder": false,
      "source": "",
      "contain": true,
      "background": "#e5e8e1",
      "gallery": true
    },
    {
      "id": "crystal-detail",
      "title": "TEM liftout detail",
      "category": "Research images",
      "thumbnail": "assets/crystal-detail.webp",
      "full": "assets/crystal-detail.webp",
      "alt": "Grayscale microscopy image of a stepped crystal surface, with the original blue border and cyan annotation.",
      "caption": "Annotated detail of the TEM liftout.",
      "credit": "Figure supplied by Éamonn Needham",
      "placeholder": false,
      "source": "",
      "contain": true,
      "background": "#e5e8e1",
      "gallery": false
    },
    {
      "id": "pyramid-field",
      "original": "image(20261007-211646).png",
      "title": "Pyramid Peak fieldwork",
      "alt": "A large light and dark intrusive rock exposure below a rocky slope at Pyramid Peak.",
      "caption": "Fieldwork at Pyramid Peak for calcium isotope and thermal–chemical diffusion modelling.",
      "category": "Field & landscapes",
      "contain": false,
      "thumbnail": "assets/pyramid-field-thumb.webp",
      "full": "assets/pyramid-field.webp",
      "credit": "From Éamonn Needham’s collection",
      "placeholder": false,
      "source": "",
      "gallery": true,
      "wide": false
    },
    {
      "id": "hood-storage",
      "original": "image(20261007-211810).png",
      "title": "Mt. Hood magma storage",
      "alt": "A schematic of a volcano and its subsurface magma-storage system, showing interconnected bodies, magma mixing, and a rigid magma sponge.",
      "caption": "Mt. Hood magma storage: Sr and Mg diffusion modelling, U–Th disequilibria dating, and Ti-in-zircon thermometry.",
      "category": "Research images",
      "contain": true,
      "thumbnail": "assets/hood-storage-thumb.webp",
      "full": "assets/hood-storage.webp",
      "credit": "From Éamonn Needham’s collection",
      "placeholder": false,
      "source": "",
      "gallery": true,
      "wide": false
    },
    {
      "id": "tecolote-thin-sections",
      "original": "image(20261007-212019).png",
      "title": "Tecolote scoria thin sections",
      "alt": "A four-by-five arrangement of scoria thin sections with contrasting vesicle and crystal textures.",
      "caption": "Thin sections of scoria from Tecolote, Pinacate volcanic field, Mexico.",
      "category": "Research images",
      "contain": true,
      "thumbnail": "assets/tecolote-thin-sections-thumb.webp",
      "full": "assets/tecolote-thin-sections.webp",
      "credit": "From Éamonn Needham’s collection",
      "placeholder": false,
      "source": "",
      "gallery": true,
      "wide": true
    },
    {
      "id": "tecolote-fragmentation",
      "original": "image(20261007-212116).png",
      "title": "Scoria fragmentation schematic",
      "alt": "A conduit fragmentation schematic comparing agglomerated, broken, and whole scoria textures with depth and viscosity gradients.",
      "caption": "Conduit fragmentation schematic with contrasting scoria textures.",
      "category": "Research images",
      "contain": true,
      "thumbnail": "assets/tecolote-fragmentation-thumb.webp",
      "full": "assets/tecolote-fragmentation.webp",
      "credit": "From Éamonn Needham’s collection",
      "placeholder": false,
      "source": "",
      "gallery": true,
      "wide": false
    },
    {
      "id": "scoria-zonation",
      "original": "image(20261007-212150).png",
      "title": "Heterogeneous zonation in scoria",
      "alt": "Colour-coded map of scoria sample 1a-09, with gold, brown, and black domains, phenocrysts, distorted suture voids, and a 2 mm scale bar.",
      "caption": "Map of heterogeneous zonation in scoria, sample 1a-09.",
      "category": "Research images",
      "contain": true,
      "thumbnail": "assets/scoria-zonation-thumb.webp",
      "full": "assets/scoria-zonation.webp",
      "credit": "From Éamonn Needham’s collection",
      "placeholder": false,
      "source": "",
      "gallery": true,
      "wide": false
    },
    {
      "id": "scoria-oxides",
      "original": "image(20261007-212215).png",
      "title": "Oxides on scoria exterior",
      "alt": "Close view of a dark vesicular scoria surface with reflective oxide patches.",
      "caption": "Oxides on the exterior of scoria.",
      "category": "Research images",
      "contain": true,
      "thumbnail": "assets/scoria-oxides-thumb.webp",
      "full": "assets/scoria-oxides.webp",
      "credit": "From Éamonn Needham’s collection",
      "placeholder": false,
      "source": "",
      "gallery": true,
      "wide": false
    },
    {
      "id": "ocellar-quartz",
      "original": "24-PP-20_ocellar_quartz_1_xpl.png",
      "title": "Ocellar quartz — XPL",
      "alt": "Cross-polarized thin-section image showing rounded quartz grains and surrounding minerals, with a 1 mm scale bar.",
      "caption": "Ocellar quartz in cross-polarized light (XPL), sample 24-PP-20.",
      "category": "Research images",
      "contain": true,
      "thumbnail": "assets/ocellar-quartz-thumb.webp",
      "full": "assets/ocellar-quartz.webp",
      "credit": "From Éamonn Needham’s collection",
      "placeholder": false,
      "source": "",
      "gallery": true,
      "wide": true
    },
    {
      "id": "pyramid-intrusion",
      "original": "c0036c74-adf9-4c4f-ba12-888476697810~1 (1).jpg",
      "title": "Pyramid Peak intrusion textures",
      "alt": "Light and dark intrusive rocks with rounded dark inclusions and intersecting pale veins exposed at Pyramid Peak.",
      "caption": "Textures in the Pyramid Peak intrusion.",
      "category": "Field & landscapes",
      "contain": true,
      "thumbnail": "assets/pyramid-intrusion-thumb.webp",
      "full": "assets/pyramid-intrusion.webp",
      "credit": "From Éamonn Needham’s collection",
      "placeholder": false,
      "source": "",
      "gallery": true,
      "wide": false
    },
    {
      "id": "lake-george",
      "original": "PXL_20260821_234021135.MP.jpg",
      "title": "Lake George",
      "alt": "A compass and topographic map on a picnic table beside Lake George, with forest and mountains behind.",
      "caption": "Lake George.",
      "category": "Field & landscapes",
      "contain": true,
      "thumbnail": "assets/lake-george-thumb.webp",
      "full": "assets/lake-george.webp",
      "credit": "From Éamonn Needham’s collection",
      "placeholder": false,
      "source": "",
      "gallery": true,
      "wide": false
    },
    {
      "id": "buttermilk-boulders",
      "original": "PXL_20260822_175742237.jpg",
      "title": "Buttermilk Boulders",
      "alt": "Rounded granite boulders, scattered shrubs, and a mountain ridge beneath scattered clouds.",
      "caption": "Buttermilk Boulders.",
      "category": "Field & landscapes",
      "contain": false,
      "thumbnail": "assets/buttermilk-boulders-thumb.webp",
      "full": "assets/buttermilk-boulders.webp",
      "credit": "From Éamonn Needham’s collection",
      "placeholder": false,
      "source": "",
      "gallery": true,
      "wide": true
    },
    {
      "id": "bishop-tuff-quarry",
      "original": "PXL_20260822_232908113.jpg",
      "title": "Bishop Tuff Quarry",
      "alt": "A pale layered quarry exposure beside dry grassland, with mountains beyond.",
      "caption": "Bishop Tuff Quarry.",
      "category": "Field & landscapes",
      "contain": false,
      "thumbnail": "assets/bishop-tuff-quarry-thumb.webp",
      "full": "assets/bishop-tuff-quarry.webp",
      "credit": "From Éamonn Needham’s collection",
      "placeholder": false,
      "source": "",
      "gallery": true,
      "wide": false
    },
    {
      "id": "ruby-lake",
      "original": "PXL_20260824_163136635.jpg",
      "title": "Ruby Lake",
      "alt": "Alpine lakes among conifers beneath steep granite peaks, viewed from a rocky trail.",
      "caption": "Ruby Lake.",
      "category": "Field & landscapes",
      "contain": false,
      "thumbnail": "assets/ruby-lake-thumb.webp",
      "full": "assets/ruby-lake.webp",
      "credit": "From Éamonn Needham’s collection",
      "placeholder": false,
      "source": "",
      "gallery": true,
      "wide": true
    },
    {
      "id": "orbicular-granite",
      "original": "PXL_20260824_233903038.jpg",
      "title": "Orbicular Granite Boulder",
      "alt": "Concentric dark and light mineral bands in a granite boulder, with a hand for scale.",
      "caption": "Orbicular Granite Boulder.",
      "category": "Field & landscapes",
      "contain": true,
      "thumbnail": "assets/orbicular-granite-thumb.webp",
      "full": "assets/orbicular-granite.webp",
      "credit": "From Éamonn Needham’s collection",
      "placeholder": false,
      "source": "",
      "gallery": true,
      "wide": false
    },
    {
      "id": "intrusion-detail",
      "original": "PXL_20260826_210029813 (1).jpg",
      "title": "Intrusion texture",
      "alt": "A circular pale-rimmed inclusion and intersecting pale veins in a rock exposure, with a boot for scale.",
      "caption": "Intrusion texture, with a boot for scale.",
      "category": "Field & landscapes",
      "contain": true,
      "thumbnail": "assets/intrusion-detail-thumb.webp",
      "full": "assets/intrusion-detail.webp",
      "credit": "From Éamonn Needham’s collection",
      "placeholder": false,
      "source": "",
      "gallery": true,
      "wide": false
    },
    {
      "id": "tem-liftout",
      "original": "T2_Liftout_014.tif",
      "title": "TEM liftout",
      "alt": "Electron microscope image of a lifted-out sample mounted for TEM work, with instrument annotations and a 5 micrometre scale bar.",
      "caption": "TEM liftout. The original instrument annotation and scale bar are retained.",
      "category": "Laboratory",
      "contain": true,
      "thumbnail": "assets/tem-liftout-thumb.webp",
      "full": "assets/tem-liftout.webp",
      "credit": "From Éamonn Needham’s collection",
      "placeholder": false,
      "source": "",
      "gallery": true,
      "wide": false
    },
    {
      "id": "sem-2a-51",
      "title": "SEM image — sample 2a-51",
      "category": "Research images",
      "thumbnail": "assets/sem-2a-51-thumb.webp",
      "full": "assets/sem-2a-51.webp",
      "alt": "Grayscale electron microscope image of a vesicular sample, with contrasting textures and the original 100 micrometre scale bar.",
      "caption": "SEM image supplied as 2a-51-x40Comp-R3-N0.tif. The full frame and original scale bar are retained.",
      "credit": "Image supplied by Éamonn Needham",
      "placeholder": false,
      "source": "",
      "contain": true,
      "gallery": true
    },
    {
      "id": "toba-cryptotephra",
      "original": "image(20261007-222200).png",
      "title": "Toba cryptotephra",
      "alt": "Microscope image of a Toba volcanic glass shard, with red crosshairs and an analysis point marked in blue.",
      "caption": "Volcanic glass shard from Toba cryptotephra.",
      "category": "Research images",
      "thumbnail": "assets/toba-cryptotephra.webp",
      "full": "assets/toba-cryptotephra.webp",
      "credit": "Image supplied by Éamonn Needham",
      "placeholder": false,
      "source": "",
      "contain": true,
      "gallery": true,
      "background": "#111713"
    },
    {
      "id": "sims-zircon",
      "original": "image(20261007-222255).png",
      "title": "Indium-mounted zircon — SIMS",
      "alt": "An elongated zircon mounted in indium, showing SIMS analysis pits and the original 100 micrometre scale bar.",
      "caption": "Indium-mounted zircon after SIMS analysis.",
      "category": "Research images",
      "thumbnail": "assets/sims-zircon.webp",
      "full": "assets/sims-zircon.webp",
      "credit": "Image supplied by Éamonn Needham",
      "placeholder": false,
      "source": "",
      "contain": true,
      "gallery": true,
      "background": "#111713"
    },
    {
      "id": "plagioclase-la-icp-ms",
      "original": "image(20261007-222348).png",
      "title": "Plagioclase — LA-ICP-MS",
      "alt": "Grayscale image of a plagioclase grain with several laser-ablation traverses across its surface.",
      "caption": "Plagioclase with laser-ablation traverses from LA-ICP-MS analysis.",
      "category": "Research images",
      "thumbnail": "assets/plagioclase-la-icp-ms.webp",
      "full": "assets/plagioclase-la-icp-ms.webp",
      "credit": "Image supplied by Éamonn Needham",
      "placeholder": false,
      "source": "",
      "contain": true,
      "gallery": true,
      "background": "#111713"
    },
    {
      "category": "Research images",
      "credit": "Figure supplied by Éamonn Needham",
      "placeholder": false,
      "source": "",
      "contain": true,
      "background": "#ffffff",
      "gallery": true,
      "id": "thermal-chemical-model",
      "title": "Thermal–chemical diffusion model",
      "alt": "Two model panels showing temperature and liquid fraction through time and distance from an intrusion contact.",
      "caption": "Thermal–chemical diffusion model: temperature and liquid fraction through time and distance.",
      "wide": true,
      "thumbnail": "assets/thermal-chemical-model.webp",
      "full": "assets/thermal-chemical-model.webp"
    },
    {
      "category": "Research images",
      "credit": "Figure supplied by Éamonn Needham",
      "placeholder": false,
      "source": "",
      "contain": true,
      "background": "#e9eae5",
      "gallery": true,
      "id": "quartz-growth-heart",
      "title": "Quartz growth experiment — heart",
      "alt": "SEM image of a heart-shaped growth feature in a quartz experiment, with a 20 micrometre scale bar.",
      "caption": "Heart-shaped feature in a quartz growth experiment. Scale bar: 20 µm.",
      "thumbnail": "assets/quartz-growth-heart.webp",
      "full": "assets/quartz-growth-heart.webp"
    },
    {
      "category": "Research images",
      "credit": "Figure supplied by Éamonn Needham",
      "placeholder": false,
      "source": "",
      "contain": true,
      "background": "#e9eae5",
      "gallery": true,
      "id": "epidosite-product",
      "title": "Epidosite experimental product",
      "alt": "SEM image of intergrown crystals in an epidosite experimental product, with a 10 micrometre scale bar.",
      "caption": "Epidosite experimental product. Scale bar: 10 µm.",
      "thumbnail": "assets/epidosite-product.webp",
      "full": "assets/epidosite-product.webp"
    }
  ],
  "projects": [
    {
      "id": "tecolote",
      "title": "Fragmentation and Scoria Formation at Tecolote",
      "field": "Volcanology",
      "image": "tecolote-thin-sections",
      "short": "Fragmentation and scoria formation in explosive basaltic eruptions.",
      "question": "How do heterogeneous fragmentation processes produce scoria?",
      "approach": "I use micro-textural analysis of scoria from Tecolote, Mexico, to investigate fragmentation and particle formation. This work identifies a scoria formation mechanism involving simultaneous brittle and ductile fragmentation at fine scales.",
      "figures": [
        "scoria-zonation",
        "scoria-oxides"
      ],
      "aliases": [],
      "displayImage": "scoria-zonation",
      "displaySummary": "Micro-textural analysis of Tecolote scoria examines particle formation and the juxtaposition of brittle and ductile fragmentation products."
    },
    {
      "id": "titaniq",
      "title": "Quartz Growth and Titanium Uptake (TitaniQ)",
      "field": "Experimental petrology",
      "image": "titaniq",
      "short": "Quartz growth, titanium incorporation, and thermobarometry.",
      "question": "When does titanium in quartz reliably record temperature and pressure?",
      "approach": "Quartz growth experiments and microscopy test how titanium is incorporated, including the role of amorphous precursors, and what these processes mean for TitaniQ thermobarometry.",
      "figures": [
        "titaniq",
        "quartz-growth-heart"
      ],
      "aliases": [
        "titaniq-project"
      ],
      "displayImage": "titaniq",
      "displaySummary": "Quartz growth experiments test titanium incorporation, the role of amorphous precursors, and the assumptions behind TitaniQ thermobarometry."
    },
    {
      "id": "mt-hood",
      "title": "Magma Storage Beneath Mt. Hood",
      "field": "Magma storage",
      "image": "hood-storage",
      "short": "Storage conditions, thermal histories, and crystal residence times.",
      "question": "How variable are magma storage conditions beneath Mt. Hood?",
      "approach": "Sr and Mg diffusion modelling, U–Th disequilibria dating, and Ti-in-zircon thermometry constrain magma storage conditions. This work identifies simultaneous warm and cold storage regimes within a single reservoir beneath Mt. Hood.",
      "figures": [
        "hood-storage"
      ],
      "aliases": [
        "mt-hood-project"
      ],
      "displayImage": "hood-storage",
      "displaySummary": "Sr–Mg diffusion modelling, U–Th dating, and Ti-in-zircon thermometry reveal simultaneous warm and cold storage within a single magma reservoir."
    },
    {
      "id": "pyramid-peak",
      "title": "Thermal–Chemical Diffusion at Pyramid Peak",
      "field": "Isotopes and diffusion",
      "image": "pyramid-field",
      "short": "Calcium isotope diffusion and the thermal evolution of an intrusion.",
      "question": "What can calcium isotope gradients tell us about intrusion cooling?",
      "approach": "Field observations and intrusion textures guide thermal and chemical diffusion modelling, linking calcium isotope variations to element transport and the thermal evolution of the intrusion.",
      "figures": [
        "pyramid-field",
        "pyramid-intrusion"
      ],
      "aliases": [
        "pyramid-peak-project"
      ],
      "displayImage": "thermal-chemical-model",
      "displaySummary": "Thermal–chemical models connect calcium isotope gradients, intrusion textures, and field observations to element transport and cooling."
    },
    {
      "id": "lunar-breccias",
      "title": "Early Lunar Magmas and Impact Modification",
      "field": "Lunar geochemistry",
      "image": "lunar-breccia",
      "short": "Testing mineral–glass relationships and impact modification.",
      "question": "Do minerals and their surrounding glass preserve a common history?",
      "approach": "Al-in-zircon systematics reveal fine-scale disequilibrium between zircons and their host melts or melt inclusions. These relationships indicate extensive impact modification of supposedly pristine lunar samples, while the zircons preserve their original compositions.",
      "figures": [
        "lunar-breccia",
        "lunar-clast"
      ],
      "url": "https://www.nature.com/articles/s41467-025-57691-z",
      "aliases": [
        "lunar"
      ],
      "displayImage": "lunar-breccia",
      "displaySummary": "Al-in-zircon systematics test whether zircons and surrounding glass share a common history, revealing impact modification while preserving records of early lunar magmas."
    },
    {
      "id": "ocellar-quartz",
      "title": "Ocellar Quartz and Magma Plumbing",
      "field": "Mineral textures",
      "image": "ocellar-quartz",
      "short": "Mineral growth and processes in magma plumbing systems.",
      "question": "What do ocellar quartz textures reveal about mineral growth?",
      "approach": "I examine these textures through field observations and petrography to investigate crystal growth and processes within magma plumbing systems.",
      "figures": [
        "ocellar-quartz"
      ],
      "aliases": [
        "ocellar-quartz-project"
      ],
      "displayImage": "ocellar-quartz",
      "displaySummary": "Field observations and petrography connect ocellar quartz textures to crystal growth and processes within magma plumbing systems."
    },
    {
      "id": "fault-healing",
      "title": "Quartz Growth, Fault Healing, and Tremor",
      "field": "Experimental petrology",
      "image": null,
      "visualLabel": "Quartz growth",
      "short": "Experiments on quartz growth, cohesion, and fault healing.",
      "question": "How does quartz growth contribute to fault healing?",
      "approach": "I use quartz growth experiments to investigate how cohesion develops over time and how progressive healing relates to tremor.",
      "figures": [],
      "aliases": [],
      "displayImage": "experiment",
      "displaySummary": "Quartz growth experiments investigate the development of cohesion and its relationship to fault healing and tremor."
    },
    {
      "id": "cryptotephra",
      "title": "Cryptotephra in the Archaeological Record",
      "field": "Cryptotephra",
      "image": "toba-cryptotephra",
      "visualLabel": "Cryptotephra",
      "short": "Sourcing volcanic glass shards in archaeological records.",
      "question": "How reliably can small glass shards identify their volcanic source?",
      "approach": "I develop trace element methods to source archaeologically significant cryptotephra and investigate how archaeological fires can modify the geochemical records preserved in volcanic glass.",
      "figures": [
        "toba-cryptotephra"
      ],
      "aliases": [],
      "displayImage": "toba-cryptotephra",
      "displaySummary": "Trace element methods source volcanic glass in archaeological records and test how heating can modify the geochemical signatures used for correlation."
    }
  ],
  "publications": [
    {
      "year": "2025",
      "title": "Pervasive impact modification of pristine lunar clasts",
      "authors": "Barboni, M., Needham, E., Trail, D., Bell, E. A., & Chen, H.-Y.",
      "journal": "Nature Communications 16, 2485.",
      "url": "https://doi.org/10.1038/s41467-025-57691-z"
    },
    {
      "year": "2022",
      "title": "In-situ U–Pb dating of zircon coronas, Sr–Nd–Hf isotopes and petrological constraints of the Daxigou anorthosite complex, NW China",
      "authors": "Yuan, Q., Zhang, C., Cheng, F., Cao, X., Needham, E., Zheng, H., & Lü, X.",
      "journal": "Gondwana Research.",
      "url": "https://www.sciencedirect.com/science/article/abs/pii/S1342937X21002574"
    }
  ],
  "portraitId": "field-portrait",
  "cvLabel": "CV · October 2026 (PDF)",
  "heroImage": "mountain-landscape",
  "galleryIntroduction": "Fieldwork, laboratory work, research figures, presentations, and outreach.",
  "aboutBackground": "I completed my Ph.D. in Geological and Planetary Sciences at Arizona State University in 2025, advised by Mélanie Barboni and Amanda Clarke. Before that, I studied at the University of Oregon, where I earned my B.S. in 2019 and began working in experimental volcanology.",
  "affiliation": "Earth and Planetary Sciences · University of California, Davis",
  "education": [
    {
      "date": "2025",
      "title": "Ph.D. in Geological and Planetary Sciences",
      "institution": "Arizona State University",
      "text": "Advisors: Mélanie Barboni and Amanda Clarke. Dissertation: A Multiscale Investigation of Geochemical and Physical Heterogeneities in Igneous Processes."
    },
    {
      "date": "2019",
      "title": "Bachelor of Science",
      "institution": "University of Oregon",
      "text": "Honors thesis: Experimental Study of Microlite Crystallization During Magma Ascent."
    }
  ],
  "methodGroups": [
    {
      "id": "mass-spectrometry",
      "title": "Mass spectrometry",
      "photos": [
        "sims-zircon",
        "plagioclase-la-icp-ms"
      ],
      "items": [
        {
          "id": "la-icp-qqq-ms",
          "name": "LA-ICP-QQQ-MS",
          "detail": "Laser ablation triple quadrupole ICP-MS; trace elements in plagioclase and glass, method development, instrument maintenance, and laboratory management."
        },
        {
          "id": "sims",
          "name": "SIMS",
          "detail": "Secondary ion mass spectrometry; zircon U–Th disequilibria, lunar zircon Pb/Pb dating, aluminum, and trace elements."
        }
      ]
    },
    {
      "id": "microscopy",
      "title": "Microscopy and imaging",
      "photos": [
        "sem-2a-51",
        "tem-liftout"
      ],
      "items": [
        {
          "id": "sem",
          "name": "SEM",
          "detail": "Scanning electron microscopy; mineral and experimental sample textures."
        },
        {
          "id": "tem",
          "name": "TEM",
          "detail": "Transmission electron microscopy."
        },
        {
          "id": "fib",
          "name": "FIB",
          "detail": "Focused ion beam sample preparation."
        },
        {
          "id": "ebsd",
          "name": "EBSD",
          "detail": "Electron backscatter diffraction; crystallographic structure and misorientation in lunar zircons."
        },
        {
          "id": "microprobe",
          "name": "Electron microprobe — EDS and WDS",
          "detail": "Major element analyses, backscattered electron imaging, and X-ray mapping."
        },
        {
          "id": "petrography",
          "name": "Petrographic microscopy",
          "detail": "Thin-section characterization, mineral textures, and selection of grains for further analysis."
        },
        {
          "id": "profilometry",
          "name": "Profilometry",
          "detail": "Surface topography measurements."
        }
      ]
    },
    {
      "id": "spectroscopy",
      "title": "Spectroscopy",
      "photos": [],
      "items": [
        {
          "id": "ftir",
          "name": "FTIR and ATR-FTIR",
          "detail": "Volatile analysis in obsidian, ATR method development, and instrument training."
        },
        {
          "id": "raman",
          "name": "Raman spectroscopy",
          "detail": "Identification of high-pressure silica polymorphs in lunar samples."
        }
      ]
    },
    {
      "id": "experimental-apparatus",
      "title": "Experimental apparatus",
      "photos": [
        "lab"
      ],
      "items": [
        {
          "id": "cold-seal",
          "name": "Cold-seal pressure vessels",
          "detail": "Rapid-quench, decompression, and stalling experiments; sample construction and apparatus operation."
        },
        {
          "id": "piston-cylinder",
          "name": "Piston-cylinder apparatus",
          "detail": "High-pressure experiments, capsule design, method development, troubleshooting, and training."
        }
      ]
    }
  ],
  "activities": [
    {
      "text": "",
      "photos": [],
      "selected": true,
      "status": "Scheduled",
      "includeScheduled": true,
      "id": "expet-2026",
      "date": "October 2026",
      "sortDate": "2026-10",
      "category": "Posters",
      "type": "Conference poster",
      "title": "Titanium-in-Quartz: Time series experiments reveal a possible non-classical crystallization pathway",
      "event": "EXPET 2026",
      "location": "Washington, D.C.",
      "authors": "Needham, É.; Watkins, J."
    },
    {
      "id": "environmental-geochemistry-2026",
      "date": "Fall 2026",
      "sortDate": "2026-09",
      "category": "Teaching",
      "type": "Course collaboration",
      "title": "Environmental Geochemistry",
      "event": "",
      "location": "",
      "authors": "",
      "text": "Course collaboration listed in the February 2026 CV.",
      "status": "Planned in the February 2026 CV",
      "photos": [],
      "selected": false
    },
    {
      "id": "sacramento-seminar-2026",
      "date": "September 2026",
      "sortDate": "2026-09",
      "category": "Talks",
      "type": "Seminar",
      "title": "Discovering Lost Lunar Magmas",
      "event": "Sacramento State University Seminar",
      "location": "Sacramento, California",
      "authors": "Needham, É.; Barboni, M.",
      "text": "",
      "status": "",
      "photos": [],
      "selected": true,
      "includeScheduled": false
    },
    {
      "text": "",
      "photos": [],
      "selected": true,
      "status": "",
      "includeScheduled": false,
      "id": "astronomy-on-tap-2026",
      "date": "August 2026",
      "sortDate": "2026-08",
      "category": "Talks",
      "type": "Public talk",
      "title": "Rediscovering Lost Lunar Magmas",
      "event": "Astronomy on Tap",
      "location": "Oakland, California",
      "authors": "Needham, É.",
      "subtitle": "and perspectives on why we should go back to the Moon"
    },
    {
      "id": "goldschmidt-2026",
      "date": "July 2026",
      "sortDate": "2026-07",
      "category": "Posters",
      "type": "Conference poster",
      "title": "Titanium-in-Quartz: Time series experiments reveal a possible non-classical crystallization pathway",
      "event": "Goldschmidt",
      "location": "Montréal, Canada",
      "authors": "Needham, É.; Watkins, J.",
      "text": "",
      "status": "",
      "photos": [],
      "selected": true,
      "includeScheduled": false
    },
    {
      "id": "davis-seminar-2026",
      "date": "May 2026",
      "sortDate": "2026-05",
      "category": "Talks",
      "type": "Department seminar",
      "title": "How Pristine Are Lunar Samples? Rethinking the Sample Record of the Early Moon",
      "event": "UC Davis Department Seminar",
      "location": "Davis, California",
      "authors": "Needham, É.; Barboni, M.; Trail, D.; Bell, E.",
      "text": "",
      "status": "",
      "photos": [],
      "selected": true,
      "includeScheduled": false
    },
    {
      "id": "davis-postdoc-2026",
      "date": "April 2026",
      "sortDate": "2026-04",
      "category": "Posters",
      "type": "Symposium poster",
      "title": "Beyond Equilibrium: Amorphous Precursor-Mediated Ti Uptake and Its Implications for TitaniQ Thermobarometry",
      "event": "UC Davis Postdoc Symposium",
      "location": "Davis, California",
      "authors": "Needham, É.; Watkins, J.",
      "text": "",
      "status": "",
      "photos": [],
      "selected": true,
      "includeScheduled": false
    },
    {
      "location": "",
      "authors": "",
      "text": "Eight guest lectures covering the formation of the universe through the rock record.",
      "status": "",
      "photos": [],
      "selected": true,
      "includeScheduled": false,
      "id": "gel1-guest-2026",
      "date": "Spring 2026",
      "sortDate": "2026-04",
      "category": "Teaching",
      "type": "Guest lecturer",
      "title": "GEL 1 — eight guest lectures",
      "event": "University of California, Davis"
    },
    {
      "location": "",
      "authors": "",
      "text": "One invited lecture on Grand Canyon geology.",
      "status": "",
      "photos": [],
      "selected": true,
      "includeScheduled": false,
      "id": "eps1-grand-canyon",
      "date": "Spring 2026",
      "sortDate": "2026-04",
      "category": "Teaching",
      "type": "Invited lecture",
      "title": "The geology of the Grand Canyon — EPS 1",
      "event": "University of California, Davis"
    },
    {
      "id": "davis-lunch-2026",
      "date": "March 2026",
      "sortDate": "2026-03",
      "category": "Talks",
      "type": "Lunch talk",
      "title": "Heterogeneous Subsurface Fragmentation Regimes in Highly Explosive Basaltic Eruptions",
      "event": "UC Davis Lunch Talk",
      "location": "Davis, California",
      "authors": "Needham, É.; Zawacki, E.; Clarke, A.; Roggensack, K.",
      "text": "",
      "status": "",
      "photos": [],
      "selected": true,
      "includeScheduled": false
    },
    {
      "id": "defense-2025",
      "date": "May 2025",
      "sortDate": "2025-05",
      "category": "Talks",
      "type": "Dissertation defense",
      "title": "A Multiscale Investigation of Geochemical and Physical Heterogeneities in Igneous Processes",
      "event": "Arizona State University",
      "location": "Phoenix, Arizona",
      "authors": "Needham, É.",
      "text": "",
      "status": "",
      "photos": [],
      "selected": true
    },
    {
      "id": "glg103-2025",
      "date": "Spring 2025",
      "sortDate": "2025-04",
      "category": "Teaching",
      "type": "Teaching assistant",
      "title": "GLG 103 laboratory",
      "event": "Arizona State University",
      "location": "",
      "authors": "",
      "text": "Three weekly labs for 95 students; developed introductory lectures and incorporated Google Earth into laboratory material.",
      "status": "",
      "photos": [],
      "selected": true
    },
    {
      "id": "lpsc-2024",
      "date": "March 2024",
      "sortDate": "2024-03",
      "category": "Talks",
      "type": "Conference talk",
      "title": "Probing the Cogeneity of Minerals and Glasses in Lunar Breccias Using Aluminum in Zircon and Glass",
      "event": "Lunar and Planetary Science Conference",
      "location": "Houston, Texas",
      "authors": "Needham, É.; Barboni, M.; Trail, D.; Bell, E.",
      "text": "",
      "status": "",
      "photos": [],
      "selected": true
    },
    {
      "id": "paleoanthropology-2024",
      "date": "March 2024",
      "sortDate": "2024-03",
      "category": "Collaborations",
      "type": "Co-authored talk",
      "title": "The potential of crypto-tephrochronology studies at paleoanthropological sites throughout Africa",
      "event": "Paleoanthropology Society",
      "location": "Los Angeles, California",
      "authors": "Hirniak, J.; Smith, E.; Johnsen, R.; Needham, É.; Barboni, M.; Marean, C.",
      "text": "",
      "status": "",
      "photos": [],
      "selected": true
    },
    {
      "id": "llamas",
      "date": "2024",
      "sortDate": "2024",
      "category": "Outreach & service",
      "type": "School outreach",
      "title": "Volcanoes and Llamas — Puppetry in the Classroom",
      "event": "",
      "location": "",
      "authors": "",
      "text": "",
      "status": "",
      "photos": [],
      "selected": true
    },
    {
      "id": "scix-2023",
      "date": "October 2023",
      "sortDate": "2023-10",
      "category": "Collaborations",
      "type": "Co-authored talk",
      "title": "The effects of archaeological fires on volcanic glass shards: An experimental approach",
      "event": "SciX",
      "location": "Reno, Nevada",
      "authors": "Hirniak, J.; Needham, É.; Karkanas, P.; Smith, E.; Campisano, C.; Marean, C.",
      "text": "",
      "status": "",
      "photos": [],
      "selected": true
    },
    {
      "id": "goldschmidt-2023",
      "date": "July 2023",
      "sortDate": "2023-07",
      "category": "Talks",
      "type": "Conference talk",
      "title": "Sr and Mg diffusion models of plagioclase show potential long melt residence time and complex mush structure beneath arc volcanoes",
      "event": "Goldschmidt",
      "location": "Lyon, France",
      "authors": "Needham, É.; Barboni, M.",
      "text": "",
      "status": "",
      "photos": [],
      "selected": true
    },
    {
      "id": "chapman-2022",
      "date": "September 2022",
      "sortDate": "2022-09",
      "category": "Posters",
      "type": "Conference poster",
      "title": "Micro-Textural Analysis of the Highly Explosive Basaltic Eruption at Tecolote, Pinacates Volcanic Field, Mexico",
      "event": "Chapman Conference on Distributed Volcanism",
      "location": "Flagstaff, Arizona",
      "authors": "Needham, É.; Zawacki, E.; Clarke, A.; Roggensack, K.",
      "text": "",
      "status": "",
      "photos": [],
      "selected": true
    },
    {
      "id": "teachers-2022",
      "date": "Summer 2022",
      "sortDate": "2022-06",
      "category": "Outreach & service",
      "type": "Teacher workshop",
      "title": "Geochronology for high school teachers",
      "event": "",
      "location": "",
      "authors": "",
      "text": "Demonstrated laser ablation, zircon geochronology, and petrographic characterization of lunar zircons for eight visiting high school teachers.",
      "status": "",
      "photos": [],
      "selected": true
    },
    {
      "id": "geol101-2022",
      "date": "Spring 2022",
      "sortDate": "2022-04",
      "category": "Teaching",
      "type": "Teaching assistant",
      "title": "GEOL 101",
      "event": "Arizona State University",
      "location": "",
      "authors": "",
      "text": "Teaching assistant for introductory geology.",
      "status": "",
      "photos": [],
      "selected": true
    },
    {
      "id": "glg103-2021",
      "date": "Spring 2021",
      "sortDate": "2021-04",
      "category": "Teaching",
      "type": "Teaching assistant",
      "title": "GLG 103 laboratory",
      "event": "Arizona State University",
      "location": "",
      "authors": "",
      "text": "Two weekly labs for 64 students, with lectures introducing each week’s laboratory material.",
      "status": "",
      "photos": [],
      "selected": false
    },
    {
      "id": "glg101-lecture-2021",
      "date": "Spring 2021",
      "sortDate": "2021-04",
      "category": "Teaching",
      "type": "Guest lecture",
      "title": "Volcanoes — GLG 101",
      "event": "Arizona State University",
      "location": "",
      "authors": "",
      "text": "An hour-long lecture for more than 100 students, combining textbook material, examples, and volcanology research.",
      "status": "",
      "photos": [],
      "selected": true
    },
    {
      "id": "agu-2020",
      "date": "December 2020",
      "sortDate": "2020-12",
      "category": "Posters",
      "type": "Conference poster",
      "title": "New perspectives on the use of triple quadrupole ICP-MS (laser and solution) systems for geochemical studies",
      "event": "American Geophysical Union",
      "location": "Online",
      "authors": "Needham, É.; Marquardt, M.; Barboni, M.",
      "text": "",
      "status": "",
      "photos": [],
      "selected": true
    },
    {
      "id": "agu-pumice-2019",
      "date": "December 2019",
      "sortDate": "2019-12",
      "category": "Collaborations",
      "type": "Co-authored poster",
      "title": "Making Pumice: a Post-Fragmentation Process?",
      "event": "American Geophysical Union",
      "location": "San Francisco, California",
      "authors": "Trafton, K.; Giachetti, T.; Needham, É.",
      "text": "",
      "status": "",
      "photos": [],
      "selected": true
    },
    {
      "id": "volcor-2019",
      "date": "May 2019",
      "sortDate": "2019-05",
      "category": "Posters",
      "type": "Conference poster",
      "title": "Experimental Study of Microlite Crystallization at Mono Craters",
      "event": "Volc-OR",
      "location": "Eugene, Oregon",
      "authors": "Needham, É.; Giachetti, T.; Watkins, J.",
      "text": "",
      "status": "",
      "photos": [],
      "selected": false
    },
    {
      "id": "sge-president",
      "date": "2018–2019",
      "sortDate": "2019",
      "category": "Outreach & service",
      "type": "Service",
      "title": "Sigma Gamma Epsilon president",
      "event": "University of Oregon",
      "location": "",
      "authors": "",
      "text": "President of the geological honor society.",
      "status": "",
      "photos": [],
      "selected": false
    },
    {
      "id": "agu-microlite-2018",
      "date": "December 2018",
      "sortDate": "2018-12",
      "category": "Posters",
      "type": "Conference poster",
      "title": "Experimental study of microlite crystallization during magma ascent",
      "event": "American Geophysical Union",
      "location": "Washington, D.C.",
      "authors": "Needham, É.; Watkins, J.; Garcia, V.; Gardner, J.; Giachetti, T.",
      "text": "",
      "status": "",
      "photos": [],
      "selected": true
    },
    {
      "location": "Washington, D.C.",
      "authors": "Olsen, E.; Needham, É.; Watkins, J.; Devriendt, L.",
      "text": "",
      "status": "",
      "photos": [],
      "selected": true,
      "includeScheduled": false,
      "id": "agu-carbonates-2018",
      "date": "December 2018",
      "sortDate": "2018-12",
      "title": "The effect of salinity on the activity of carbonic anhydrase and δ¹⁸O of carbonates",
      "event": "American Geophysical Union",
      "category": "Collaborations",
      "type": "Co-authored poster"
    },
    {
      "id": "gsa-obsidian-2018",
      "date": "November 2018",
      "sortDate": "2018-11",
      "category": "Collaborations",
      "type": "Co-authored poster",
      "title": "Obsidian pyroclasts: pre-eruptive vanguard magma, or juvenile clasts formed after fragmentation?",
      "event": "Geological Society of America",
      "location": "Indianapolis, Indiana",
      "authors": "Wiejaczka, J.; Giachetti, T.; Watkins, J.; Gardner, J.; Trafton, K.; Needham, É.",
      "text": "",
      "status": "",
      "photos": [],
      "selected": true
    },
    {
      "location": "Boston, Massachusetts",
      "authors": "Watkins, K.; Olsen, E.; Needham, É.",
      "text": "",
      "status": "",
      "photos": [],
      "selected": true,
      "includeScheduled": false,
      "id": "goldschmidt-calcite-2018",
      "date": "August 2018",
      "sortDate": "2018-08",
      "title": "Calcite precipitation from saline solutions: How dissolved NaCl affect DIC speciation, DIC isotopic equilibration, and δ¹⁸O in calcite",
      "event": "Goldschmidt",
      "category": "Collaborations",
      "type": "Co-authored poster"
    },
    {
      "id": "volcor-2018",
      "date": "April 2018",
      "sortDate": "2018-04",
      "category": "Posters",
      "type": "Conference poster",
      "title": "Determining the Mono Craters decompression rate: microlite and bubble number densities",
      "event": "Volc-OR",
      "location": "Corvallis, Oregon",
      "authors": "Needham, É.; Giachetti, T.; Watkins, J.",
      "text": "",
      "status": "",
      "photos": [],
      "selected": false
    },
    {
      "id": "virginia-2018",
      "date": "Winter 2018",
      "sortDate": "2018-01",
      "category": "Outreach & service",
      "type": "School outreach",
      "title": "Virginia Homeschool Collective",
      "event": "Virginia",
      "location": "",
      "authors": "",
      "text": "Geology lessons for students aged 7–15, followed by a field trip to search for fossil shark teeth in Potomac River deposits.",
      "status": "",
      "photos": [],
      "selected": true
    },
    {
      "id": "sge-liaison",
      "date": "2017–2018",
      "sortDate": "2018",
      "category": "Outreach & service",
      "type": "Service",
      "title": "Sigma Gamma Epsilon faculty liaison",
      "event": "University of Oregon",
      "location": "",
      "authors": "",
      "text": "Charter member and faculty liaison.",
      "status": "",
      "photos": [],
      "selected": false
    },
    {
      "id": "geology-club",
      "date": "2017–2018",
      "sortDate": "2018",
      "category": "Outreach & service",
      "type": "Service",
      "title": "Geology Club president",
      "event": "University of Oregon",
      "location": "",
      "authors": "",
      "text": "",
      "status": "",
      "photos": [],
      "selected": false
    },
    {
      "location": "Seattle, Washington",
      "authors": "Olsen, E.; Needham, É.; Watkins, J.",
      "text": "",
      "status": "",
      "photos": [],
      "selected": true,
      "includeScheduled": false,
      "id": "gsa-calcite-2017",
      "date": "October 2017",
      "sortDate": "2017-10",
      "title": "Quantifying the salinity effect on isotope fractionation during inorganic calcite precipitation",
      "event": "Geological Society of America",
      "category": "Collaborations",
      "type": "Co-authored poster"
    },
    {
      "id": "dos-rios-2017",
      "date": "Fall 2017",
      "sortDate": "2017-09",
      "category": "Outreach & service",
      "type": "School outreach",
      "title": "Dos Rios Elementary School",
      "event": "Oregon",
      "location": "",
      "authors": "",
      "text": "Lessons and demonstrations on minerals, volcanoes, earthquakes, and topography, followed by a field trip to a local outcrop.",
      "status": "",
      "photos": [],
      "selected": true
    },
    {
      "id": "gold-mountain",
      "date": "",
      "sortDate": "",
      "category": "Outreach & service",
      "type": "Outreach",
      "title": "Land survey of Gold Mountain for a future geologic interpretive site",
      "event": "",
      "location": "",
      "authors": "",
      "text": "",
      "status": "",
      "photos": [],
      "selected": false
    },
    {
      "id": "research-fellows",
      "date": "",
      "sortDate": "",
      "category": "Outreach & service",
      "type": "Invited panel",
      "title": "Panel for Presidential Undergraduate Research Fellows",
      "event": "",
      "location": "",
      "authors": "",
      "text": "",
      "status": "",
      "photos": [],
      "selected": false
    },
    {
      "id": "graduation-speaker",
      "date": "",
      "sortDate": "",
      "category": "Outreach & service",
      "type": "Invited talk",
      "title": "Geology Department graduation speaker",
      "event": "University of Oregon",
      "location": "",
      "authors": "",
      "text": "",
      "status": "",
      "photos": [],
      "selected": false
    },
    {
      "id": "breakfast-buddies",
      "date": "",
      "sortDate": "",
      "category": "Outreach & service",
      "type": "School outreach",
      "title": "Breakfast Buddies",
      "event": "Dos Rios Elementary School",
      "location": "",
      "authors": "",
      "text": "",
      "status": "",
      "photos": [],
      "selected": false
    },
    {
      "id": "science-factory",
      "date": "",
      "sortDate": "",
      "category": "Outreach & service",
      "type": "Volunteer outreach",
      "title": "Halloween Mad Scientist",
      "event": "Science Factory",
      "location": "",
      "authors": "",
      "text": "",
      "status": "",
      "photos": [],
      "selected": false
    },
    {
      "id": "volcor-liaison",
      "date": "",
      "sortDate": "",
      "category": "Outreach & service",
      "type": "Service",
      "title": "Volc-OR undergraduate liaison",
      "event": "Volc-OR",
      "location": "",
      "authors": "",
      "text": "",
      "status": "",
      "photos": [],
      "selected": false
    },
    {
      "id": "gem-showcase",
      "date": "",
      "sortDate": "",
      "category": "Outreach & service",
      "type": "Outreach",
      "title": "Gem and Mineral Showcase organizer",
      "event": "University of Oregon",
      "location": "",
      "authors": "",
      "text": "",
      "status": "",
      "photos": [],
      "selected": false
    }
  ],
  "activityIntroduction": "Presentations, university teaching, collaborative work, and public geology.",
  "researchIntroduction": "My research treats physical and chemical heterogeneity as a fundamental feature of igneous systems. I combine experiments, imaging, and geochemistry to test the assumptions behind our methods and identify when simplification obscures the processes recorded in rocks.",
  "researchCategories": [
    {
      "id": "volcanology",
      "title": "Volcanology",
      "image": "tecolote-thin-sections",
      "projectIds": [
        "tecolote",
        "cryptotephra"
      ]
    },
    {
      "id": "experimental-petrology",
      "title": "Experimental Petrology",
      "image": "titaniq",
      "projectIds": [
        "titaniq",
        "fault-healing"
      ]
    },
    {
      "id": "geochemistry",
      "title": "Geochemistry & Petrology",
      "image": "lunar-clast",
      "projectIds": [
        "lunar-breccias",
        "ocellar-quartz"
      ]
    },
    {
      "id": "modelling",
      "title": "Modelling",
      "image": "thermal-chemical-model",
      "projectIds": [
        "mt-hood",
        "pyramid-peak"
      ]
    },
    {
      "id": "methods",
      "title": "Methods / Instruments",
      "image": "lab",
      "projectIds": []
    }
  ],
  "methodsIntroduction": "",
  "modellingTools": [
    {
      "id": "diffusion-modelling",
      "name": "Diffusion modelling",
      "detail": "Sr and Mg in plagioclase; calcium isotope diffusion."
    },
    {
      "id": "thermal-modelling",
      "name": "Thermal–chemical modelling",
      "detail": "Intrusion cooling and element transport."
    },
    {
      "id": "python",
      "name": "Python",
      "detail": "Numerical models and data analysis."
    }
  ],
  "cvVersion": "October 2026",
  "cvDownloadName": "eamonn-needham-cv-oct-2026.pdf",
  "methodPhotos": [
    "sims-zircon",
    "tem-liftout",
    "epidosite-product"
  ],
  "tourGuiding": {
    "title": "Grand Canyon tour guiding",
    "company": "Across Arizona Tours",
    "text": "As a tour guide with Across Arizona Tours, I shared the geology of the Grand Canyon with visitors, connecting the rocks and landscape to the processes that shaped them.",
    "photos": [],
    "reviews": []
  },
  "professionalIdentity": "Volcanologist, Geochemist, and Experimental Petrologist"
};
